services:

  postgres:
    image: pgvector/pgvector:0.8.6-pg17
    container_name: rag-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword
    ports:
      - "5432:5432"

    volumes:
      - rag_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isreadt -U raguser -d ragdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  rag_postgres_data: